version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloack:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8765:8765"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./data/keycloack:/opt/keycloak/data/import
    command:
      - "start-dev --proxy edge --http-relative-path /auth --http-port 8765 --import-realm"

