version: '3.8'

services:
  web:
    build: .
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello_flask_dev
  nginx_rproxy: 
    image: nginx:latest
    container_name: nginx_rproxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- ./www:/data/www  
    ports:
      - 80:80
  mykeycloak:
    image: jboss/keycloak:latest
    container_name: mykeycloak
    restart: unless-stopped    
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy
      - DB_VENDOR=postgresql      
      - DB_ADDR=my-sql-host      
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_PASSWORD=${DB_KEYCLOAK_PASSWORD} 
      - DB_KEYCLOAK_USER=keycloak

volumes:
  postgres_data: