###
GET localhost:8090/poulpy/pp_blue

###
GET localhost:8090/poulpy


###
GET localhost:8090/poulpy/12


###
PUT localhost:8090/poulpy
Content-Type: application/json

{
"name":"coucou",
"color": "BLUE"
}

###
DELETE localhost:8090/poulpy/BLUE
